-- MySQL Script generated by MySQL Workbench
-- 11/19/15 19:13:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema turismo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema turismo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `turismo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `turismo` ;

-- -----------------------------------------------------
-- Table `turismo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id do usuário (pk)',
  `email` VARCHAR(45) NOT NULL COMMENT 'email do usuário (deve ser único)',
  `senha` VARCHAR(256) NOT NULL COMMENT 'senha do usuário',
  `alias` VARCHAR(20) NOT NULL COMMENT 'alias do usuário (deve ser único)',
  `nome` VARCHAR(50) NOT NULL COMMENT 'nome do usuário',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `alias_UNIQUE` (`alias` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`tipo_agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`tipo_agenda` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id do tipo de agenda (pk)',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'descrição do tipo de agenda.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`agenda` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id da agenda criada pelo usuário (pk)',
  `usuario_id` BIGINT NOT NULL COMMENT '',
  `id_tipo_agenda` INT NOT NULL COMMENT 'id do tipo de agenda (fk_agenda_tipo_agenda)',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'descricao da agenda',
  `data_inicio` DATETIME NOT NULL COMMENT 'data e hora de início prevista para a agenda',
  `data_fim` DATETIME NULL COMMENT 'data e hora de término prevista para a agenda',
  `data_criacao_agenda` DATETIME NOT NULL COMMENT 'data e hora de criação da agenda',
  PRIMARY KEY (`id`, `usuario_id`)  COMMENT '',
  INDEX `fk_agenda_tipo_agenda_idx` (`id_tipo_agenda` ASC)  COMMENT '',
  INDEX `fk_agenda_usuario_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_agenda_tipo_agenda`
    FOREIGN KEY (`id_tipo_agenda`)
    REFERENCES `turismo`.`tipo_agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `turismo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`percurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`percurso` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id do percurso (pk)',
  `agenda_id` BIGINT NOT NULL COMMENT '',
  `data_inicio` DATETIME NOT NULL COMMENT 'data e hora previstas para início do percurso',
  `data_fim` DATETIME NULL COMMENT 'data e hora previstas para o término do percurso',
  `ponto_partida` VARCHAR(50) NOT NULL COMMENT 'ponto de partida (pode conter dado de geolocalização ou informação digitada pelo usuário)',
  `ponto_chegada` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`id`, `agenda_id`)  COMMENT '',
  INDEX `fk_percurso_agenda1_idx` (`agenda_id` ASC)  COMMENT '',
  CONSTRAINT `fk_percurso_agenda1`
    FOREIGN KEY (`agenda_id`)
    REFERENCES `turismo`.`agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`tipo_transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`tipo_transporte` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id do tipo de transporte (pk).\nEx.: carro, avião, a pé, etc.',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'Referente ao tipo de transporte utilizado. Ex.: aéreo, terrestre, etc.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`transporte` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id do transporte (pk)',
  `id_tipo_transporte` INT NOT NULL COMMENT 'id do tipo de transporte descrito (fk_transporte_tipo_transporte).',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'Referente ao meio de transporte utilizado.\nEx.: avião, carro, ônibus, etc ...\n',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_transporte_tipo_transporte_idx` (`id_tipo_transporte` ASC)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '',
  CONSTRAINT `fk_transporte_tipo_transporte`
    FOREIGN KEY (`id_tipo_transporte`)
    REFERENCES `turismo`.`tipo_transporte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`trecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`trecho` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id do trecho (pk).\nTrecho é a parte do percurso que contém as informações referentes a cada ponto de interesse informado.',
  `percurso_id` BIGINT NOT NULL COMMENT '',
  `percurso_agenda_id` BIGINT NOT NULL COMMENT '',
  `id_transporte` BIGINT NOT NULL COMMENT 'id do transporte utilizado para percorrer o trecho informado (fk_trecho_transporte).',
  `ponto_partida` VARCHAR(50) NOT NULL COMMENT 'Ponto de partida(inicial) do trecho informado. Pode ser por geolocalização ou descrição simples realizada pelo usuário.',
  `ponto_chegada` VARCHAR(50) NOT NULL COMMENT 'Ponto de chegada(final) do trecho informado. Pode ser por geolocalização ou descrição simples realizada pelo usuário.',
  `distancia` INT NOT NULL COMMENT 'Distância percorrida, em metros, entre o ponto de partida e o ponto de chegada para esse trecho.',
  PRIMARY KEY (`id`, `percurso_id`, `percurso_agenda_id`)  COMMENT '',
  INDEX `fk_trecho_transporte_idx` (`id_transporte` ASC)  COMMENT '',
  INDEX `fk_trecho_percurso1_idx` (`percurso_id` ASC, `percurso_agenda_id` ASC)  COMMENT '',
  CONSTRAINT `fk_trecho_transporte`
    FOREIGN KEY (`id_transporte`)
    REFERENCES `turismo`.`transporte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trecho_percurso1`
    FOREIGN KEY (`percurso_id` , `percurso_agenda_id`)
    REFERENCES `turismo`.`percurso` (`id` , `agenda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`ponto_interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`ponto_interesse` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id do ponto de interesse (pk)',
  `id_trecho` BIGINT NOT NULL COMMENT 'id do trecho relacionado ao ponto de interesse (fk_ponto_interesse_trecho)',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'descrição do ponto de interesse',
  `localizacao` VARCHAR(60) NOT NULL COMMENT 'Localização do ponto de interesse. Pode ser por geolocalizacao ou inserção manual do usuário.',
  `custo` DECIMAL(9,2) NULL COMMENT 'O custo referente ao ponto de interesse, se houver.',
  `observacao` VARCHAR(50) NULL COMMENT 'observação sobre o ponto de interesse, se houver.',
  `data_saida` DATETIME NULL COMMENT 'data e hora de chegada no ponto de interesse informado.',
  `data_chegada` DATETIME NULL COMMENT 'data e hora de saída no ponto de interesse informado.',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_ponto_interesse_trecho_idx` (`id_trecho` ASC)  COMMENT '',
  CONSTRAINT `fk_ponto_interesse_trecho`
    FOREIGN KEY (`id_trecho`)
    REFERENCES `turismo`.`trecho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`avaliacao` (
  `id` BIGINT NOT NULL COMMENT '',
  `descricao` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`avaliacao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`avaliacao_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `usuario_id` BIGINT NOT NULL COMMENT '',
  `ponto_interesse_id` BIGINT NOT NULL COMMENT '',
  `avaliacao_id` BIGINT NOT NULL COMMENT '',
  `comentario` VARCHAR(100) NULL COMMENT 'descrição da avaliação.\nEx.: bom, ruim, excelente, etc.',
  `recomendar` TINYINT(1) NULL COMMENT '',
  `data_avaliacao` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `usuario_id`, `ponto_interesse_id`)  COMMENT '',
  INDEX `fk_avaliacao_ponto_interesse_idx` (`ponto_interesse_id` ASC)  COMMENT '',
  INDEX `fk_avaliacao_usuario1_idx` (`usuario_id` ASC)  COMMENT '',
  INDEX `fk_avaliacao_usuario_avaliacao1_idx` (`avaliacao_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avaliacao_ponto_interesse`
    FOREIGN KEY (`ponto_interesse_id`)
    REFERENCES `turismo`.`ponto_interesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `turismo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario_avaliacao1`
    FOREIGN KEY (`avaliacao_id`)
    REFERENCES `turismo`.`avaliacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`tipo_hospedagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`tipo_hospedagem` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id do tipo de hospedagem (pk)',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'descrição do tipo de hospedagem.\nEx.: Hotel, hostel, model, particular, etc.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`hospedagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`hospedagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `ponto_interesse_id` BIGINT NOT NULL COMMENT '',
  `tipo_hospedagem_id` INT NOT NULL COMMENT '',
  `reservado` TINYINT(1) NOT NULL COMMENT 'flag para identificar se a hospedagem já foi reservada',
  `paga` TINYINT(1) NOT NULL COMMENT 'flag para identificar se a hospedagem já foi paga.',
  PRIMARY KEY (`id`, `ponto_interesse_id`)  COMMENT '',
  INDEX `fk_hospedagem_tipo_hospedagem1_idx` (`tipo_hospedagem_id` ASC)  COMMENT '',
  CONSTRAINT `fk_hospedagem_ponto_interesse`
    FOREIGN KEY (`ponto_interesse_id`)
    REFERENCES `turismo`.`ponto_interesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospedagem_tipo_hospedagem`
    FOREIGN KEY (`tipo_hospedagem_id`)
    REFERENCES `turismo`.`tipo_hospedagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`especialidade` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id da especialidade (pk)',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'descrição da especialidade',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`alimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`alimentacao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `ponto_interesse_id` BIGINT NOT NULL COMMENT '',
  `especialidade_id` INT NOT NULL COMMENT '',
  `descricao` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `ponto_interesse_id`)  COMMENT '',
  INDEX `fk_alimentacao_especialidade1_idx` (`especialidade_id` ASC)  COMMENT '',
  CONSTRAINT `fk_alimentacao_ponto_interesse`
    FOREIGN KEY (`ponto_interesse_id`)
    REFERENCES `turismo`.`ponto_interesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alimentacao_especialidade1`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `turismo`.`especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`tipo_passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`tipo_passeio` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id do tipo de passeio (pk)',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'descrição do tipo de passeio.\nEx.: cultural, lazer, ponto turístico, etc.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`passeio` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `ponto_interesse_id` BIGINT NOT NULL COMMENT '',
  `id_tipo_passeio` INT NOT NULL COMMENT 'id do tipo de passeio (fk_passeio_tipo_passeio)',
  `descricao` VARCHAR(50) NOT NULL COMMENT '',
  INDEX `fk_passeio_tipo_passeio_idx` (`id_tipo_passeio` ASC)  COMMENT '',
  PRIMARY KEY (`id`, `ponto_interesse_id`)  COMMENT '',
  CONSTRAINT `fk_passeio_tipo_passeio`
    FOREIGN KEY (`id_tipo_passeio`)
    REFERENCES `turismo`.`tipo_passeio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passeio_ponto_interesse`
    FOREIGN KEY (`ponto_interesse_id`)
    REFERENCES `turismo`.`ponto_interesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`negocios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`negocios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `ponto_interesse_id` BIGINT NOT NULL COMMENT '',
  `reuniao` TINYINT(1) NULL COMMENT 'Informa se o ponto de interesse de negócio é uma reunião ou não.',
  PRIMARY KEY (`id`, `ponto_interesse_id`)  COMMENT '',
  CONSTRAINT `fk_negocios_ponto_interesse1`
    FOREIGN KEY (`ponto_interesse_id`)
    REFERENCES `turismo`.`ponto_interesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`tipo_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`tipo_evento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id do tipo de evento (pk)',
  `descricao` VARCHAR(50) NOT NULL COMMENT 'Relação dos tipos de evento.\nEx.: Acadêmico, Show, Outros, etc.',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`evento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `ponto_interesse_id` BIGINT NOT NULL COMMENT '',
  `tipo_evento_id` INT NOT NULL COMMENT '',
  `descricao` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `ponto_interesse_id`)  COMMENT '',
  INDEX `fk_evento_tipo_evento1_idx` (`tipo_evento_id` ASC)  COMMENT '',
  CONSTRAINT `fk_evento_ponto_interesse1`
    FOREIGN KEY (`ponto_interesse_id`)
    REFERENCES `turismo`.`ponto_interesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_tipo_evento`
    FOREIGN KEY (`tipo_evento_id`)
    REFERENCES `turismo`.`tipo_evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `turismo`.`preferencias_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turismo`.`preferencias_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'id da preferência do usuário',
  `usuario_id` BIGINT NOT NULL COMMENT '',
  `ponto_interesse_id` BIGINT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `usuario_id`, `ponto_interesse_id`)  COMMENT '',
  INDEX `fk_preferencias_usuario_usuario1_idx` (`usuario_id` ASC)  COMMENT '',
  INDEX `fk_preferencias_usuario_ponto_interesse1_idx` (`ponto_interesse_id` ASC)  COMMENT '',
  CONSTRAINT `fk_preferencias_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `turismo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferencias_usuario_ponto_interesse1`
    FOREIGN KEY (`ponto_interesse_id`)
    REFERENCES `turismo`.`ponto_interesse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
